### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kopardev** [ryanlayer/giggle#52]
Everything worked as expected until I had more than 1 million lines in my query file for "**giggle search**". Then it crashed with **Segmentation Fault**. After trying to do some quick debugging with gdb, I get the following backrace:

```
(gdb) backtrace
#0  0x0000000000408f30 in giggle_leaf_data_get_intersection_size ()
#1  0x0000000000408893 in giggle_collect_intersection_data_in_block ()
#2  0x000000000040882e in giggle_search ()
#3  0x000000000040a204 in giggle_query ()
#4  0x0000000000417eaa in search_main ()
#5  0x000000000040403a in main ()
```

Any help is appreciated. My original **giggle** command line was something like this:

```
giggle search -i mm10_tf_giggle_index -q tmp.1.5m.bed.gz
```

**Comment by ryanlayer** [comment]
Do you think you ran out of memory? Can you try recompiling so you get line
numbers in gdb?
